### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by Silinil** [WesCook/Homestead#86] opened 2018-02-23 22:48 UTC
I am unable to load this modpack. It finishes the loading screen then shuts down and goes back to the ATLauncher.
[crash-2018-02-23_16.41.58-client.txt](https://github.com/WesCook/Homestead/files/1753369/crash-2018-02-23_16.41.58-client.txt)

**Comment by WesCook** [comment] 2018-02-24 04:35
The error here seems to be related to generation of the texture atlas:

>Caused by: net.minecraft.util.ReportedException: Generating mipmaps for frame

I'm not sure what might be causing it though, and haven't seen it reported before.

I have a couple suggestions for things to try though.

First, I'd disabled mipmapping if it's been enabled.  It should be disabled by default, but maybe something has screwed up.  You can do so by setting `mipmapLevels` in the options.txt file.

If that fails or is not applicable, I'd disable FoamFix.  This mod really helps with memory optimization but perhaps one of those optimizations is causing problems for you.

If *that* fails, then I'd suggest two other options:

1. Try disabling the Resource Loader mod.  Simply add `.disabled` to the filename to ensure it's not loaded.
2. WTF's Expedition loads a custom resource pack as well.  You could try moving it from the resource packs directory so it isn't loaded.

Either of these actions will break game textures and make things fairly unplayable, but it will at least let you know if the crashing is caused by one of these processes anyway.

If none of these suggestions work, then unfortunately I'm out of ideas.  I would just Google search that error text above and see if there's anything else that might be relevant to you.

Please let me know if you find a working solution.

Thank you.

**Comment by Silinil** [comment] 2018-02-24 14:08
Reinstalling it and removing foamfix seems to have fixed it for me. It loaded and I'm looking forward to playing your pack! thanks!!

**Comment by WesCook** [comment] 2018-02-24 14:09
Wonderful, thanks for the update.  :)

**Closed as completed by WesCook** 2018-02-24 14:09 UTC
