### ISSUE TITLE
Command /give make item twice.

### ISSUE THREAD

**Issue by darknat** [WesCook/Homestead#7] opened 2017-07-15 11:03 UTC
Hmm, I've update your modpack, and i continue to create a map with him, but when I want use command /give, the game give me twice item :/.
One in my inventory and one on the floor.

you know this bug ?

Thank you

EDIT : I see your post with bug of animania and dsound, I have a same bug crash, how you resolve this ?

**Comment by WesCook** [comment] 2017-07-15 12:54
Hi darknat,

The first bug you described is known.  It's caused by the Item Buoyancy feature of Better With Mods.  This feature can be disabled in the configs if you'd like to correct the problem, but otherwise there is no easy fix.

Here is the relevant bug on BWM's tracker: https://github.com/BeetoGuy/BetterWithMods/issues/248

Regarding your edit, this crash has been corrected in v1.3 of Homestead.  Can you make sure you're fully up to date?

I'm going to mark this as closed as there's nothing else I can do from my end.  Though thanks for the report.

**Closed as completed by WesCook** 2017-07-15 12:54 UTC
