### ISSUE TITLE
Singleplayer world stops functioning

### ISSUE THREAD

**Issue by MayonezReyiz** [WesCook/Homestead#102] opened 2020-01-25 23:12 UTC
I was playing without a problem and then suddenly my save just stopped working, it is like server is laggy and I have high ping but I am on singleplayer. Basically chunks don't load, mobs stop moving, blocks don't drop.I waited around 5 minutes but it doesn't go away, and I also tried to save and quit but game freezes, doesn't respond and crashes.When I go back into world from last safe save, its fine for 30 seconds and then it happens again.I think something triggers this I don't know what. I can give any file you need to check.

**Comment by WesCook** [comment] 2020-01-25 23:26
It sounds like something in the world is crashing your game.  You may be able to teleport your character a distance away from that chunk, or edit the position in your player file's NBT.  If that solves the crashing then you'll know that a block or entity in the world is creating the problem.

If so, MCEdit can be used to remove that block or entity and hopefully solve the problem.

However, this is an arduous process.  It would be a lot easier and faster to roll back to a previous backup if one is available.  I know you mentioned a previous safe save, but if possible I'd try going even further back.  At worst any progress you've made could be restored quickly enough using creative mode, guilt-free.

These issues are always difficult to track down so I wish you luck.  This pack is mostly in maintenance mode now so I'm not likely to push a new update.

**Comment by MayonezReyiz** [comment] 2020-01-26 01:28
I have some backups I hope those will work but I was in same biome or chunk for several hours I didn't go far or explored I was around the village all the time, so why would that happen suddenly

**Comment by MayonezReyiz** [comment] 2020-01-26 01:58
I realized it really was something in the world, I safe loaded the world and did everything I usually do, no problem.When I go to swamp just behind the village game brokes again.

This is how it looks in game, I can't even use the chat I've never seen anything like this.

![2020-01-26_04 46 58](https://user-images.githubusercontent.com/60302214/73129569-5f357680-3ff8-11ea-9ca2-df379db3fbeb.png)

![2020-01-26_04 47 21](https://user-images.githubusercontent.com/60302214/73129570-5f357680-3ff8-11ea-9040-c317552d1abc.png)

**Comment by WesCook** [comment] 2020-01-26 11:26
It looks like the internal server is crashing.  So yeah, an entity or block.

>When I go to swamp just behind the village game brokes again.

Okay, so you have a general area.  You can try and work with McEdit to start deleting things from the world.  One idea is to just delete a few chunks from that area and let the game regenerate them, and see if that resolves the issue.

**Comment by MayonezReyiz** [comment] 2020-01-26 19:56
Well I have no idea how to use mcedit and still probably still won't fix it, so I started a new world with same seed and went to the same place and same thing happened.I think something wrong about the seed or something in the world, if you can find the source please fix it permamently so we won't see it in other worlds.


Seed is -6177723472720351006
I used realistic generation (default in modpack)
Game crashes around 90 70 -393

Thank you for your effort

**Comment by WesCook** [comment] 2020-01-27 23:28
Well as I mentioned the pack is in maintenance mode so it's unlikely I'll be pushing an update, barring something major.  I understand this is reproducible but it also appears quite rare as it's not been reported otherwise in the 2.5 years since release.

However, I'll keep this issue open so that if I do decide to make another release, I can take a look at it then.

Thank you for reporting it and investigating the issue on your side.  I hope through some combination of backups, external tools, and creative mode you can save your progress in the pack and continue playing.

**Comment by WesCook** [comment] 2022-05-08 01:33
As it's been an additional two years, I'll close this issue at this time.  If anyone else experiences the specific crash above though, please do feel free to chime in.

**Closed as completed by WesCook** 2022-05-08 01:33 UTC
