### ISSUE TITLE
sound system crashed!

### ISSUE THREAD

**Issue by crashoverride81** [WesCook/Homestead#53] opened 2017-10-18 19:43 UTC
yeah i have no clue what this is about but happens to me not to often but when it does my game freezes till it recovers from the crash! there is no set circumstances to create the bug..it just happens..i have notmal sounds outside of the game like youtube and music from spotify but the game sound system crashes and then recovers!

**Comment by WesCook** [comment] 2017-10-18 20:18
This is crash and recovery feature from Dynamic Surroundings.  Unfortunately I'm not sure what causes the sound system crash, so it's a difficult issue to debug.

Is the problem you're reporting new to the recently-released Homestead v1.7, or has it also occurred on previous versions?  I'd like to know if this is a new problem or not.

Thank you.

**Comment by crashoverride81** [comment] 2017-10-18 20:20
have not had it happen yet in 1.7 but it happened mostly in 1.6

**Comment by WesCook** [comment] 2017-10-18 20:41
Thanks for the update.  I did make a change in 1.7 to disable the chat messages from Dynamic Surroundings.  While I'd seen the "Sound system crash" notice before, it was rare and I'd never noticed the associated lag spike that you reported.  Now I'm wondering if it would have been better to have left the chat notice enabled, to explain the sudden lag for users like yourself.

If debugging the issue it would probably be best for you to re-enable that settings, and I'll consider doing the same in the next version.

https://github.com/WesCook/Homestead/blob/master/config/dsurround/dsurround.cfg#L215-L216

My suggestion for now would be to try updating to the latest version of the pack, and after some experience letting me know if the problem still persists.  Unfortunately it likely will, but it's possible a bug fix in one of the mod updates may have had an effect.

Though the unfortunate reality is that the issue is largely outside of my control.  If there's a common cause I can try and eliminate it from the pack, though only @OreCruncher has a decent understanding of that system.

I don't know if it's caused by too many sounds, or a null sound file.  As I can't consistently replicate the crash myself, I can't test for what might be causing it.

I'll leave this issue open for now to collect some more information, though may need to close the issue as unsolvable in the future.  Thank you for your patience in this matter.

**Comment by OreCruncher** [comment] 2017-10-18 21:01
Actually the bug is down in the PaulsCode sound library that Minecraft uses.  The reason is that it shows up as much as it does with Dynamic Surroundings and other sound related mods (like Ambient Sounds) is because these mods use a lot of streaming sounds (music, background biome sound, etc.)  With Vanilla Minecraft the only streaming sounds is the mood music but since only a single sound clip plays at a time the chances of running into this bug is pretty remote, but possible.  Paul (author of the PaulsCode sound library) is aware of the issue and will address at some point.  No schedule.

For posterity, I noticed this particular bug in 1.7.10 Minecraft.  It's been around a long time.

**Comment by WesCook** [comment] 2017-10-18 21:15
Much thanks for the explanation.  I remember that vanilla also had issues with sound disappearing when there is too many mobs, so that does make sense.  Modded Minecraft has a way of exaggerating the bugs hidden in vanilla (or vanilla libraries, as the case may be).

It seems like this one is outside of both of our control, so I'm going to close this.  Thanks again for the info though - that's very useful knowledge.  Hopefully Paul is able to make some progress on that one.

**Closed as completed** 2017-10-18 21:15 UTC
