### ISSUE TITLE
FoamFix is causing "no more than 2gb used" bug

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#34] opened 2017-08-24 18:20 UTC
So as you know i reported to you multiple times this "no more than 2gb used" problem. 

I didn't give up, i ask on reddit and i found the problem. It's FoamFix. 

This screen is with FoamFix: http://imgur.com/VIbWYrt

This is without: http://imgur.com/pGL3Enm

Apparently FoamFix is not properly working in this pack for some reasons. It tries to lower too aggressively ram causing the game to use only 2gb of memory even if 4gb are properly allocated on a 64bit environment. 
**This mod is used in other even bigger modpacks so i guess it's a MAJOR INCOMPATIBILITY with something specific of this pack**. 

I strongly recommend to remove this mod from the pack, until the incompatibility is discovered.  

YEEE! So happy, i can finally play this GREAT MODPACK!

Anyway i think finding the incompatibility could be very important. 
FoamFix is vastly used in other packs because it's trusted well know mod.
Maybe it's nothing but an incompatibilty could mean that there's a mod or more than one that may interfere with memory usage in a bad way. Maybe not. 
But a further investigation is vital in my opinion. Your modpack use a lot of minor mods that may have unknow memory leaks so i guess removing FoamFix is a solution but there could be an hidden problem left behind.

**Comment by nedellis** [comment] 2017-08-24 18:36
No wait. Bad news. Threshold is now at 3000ish...OMG!

It never goes up 3000 now. It's vastly better but memory behave it's still wrong. I want to die now!

**Comment by WesCook** [comment] 2017-08-24 18:50
Thanks for doing some investigative work.  I've not been impacted by framerate drops by the 2GB "soft cap", so it's strange that it would affect you.  A memory limit should affect everybody equally, I would expect.  I have a few suggestions if you'd like to experiment further.

This seems to be a product of the garbage collector, so I'd suggest trying the alternative options.  There's a few popular GC's, but G1C1 and Mark and Sweep are the most two common options.

If you'd like to work the Foamfix angle, you could check which optimization it's applying (by modifying the config file and testing) to get an idea of what affects that value.  I doubt this will give an answer by itself, but it could give a push in the right direction.

Another idea is that it may just be soft capping at 50% of your max, and not actually 2GB.  What happens if you set the cap to 8GB instead?  Can it use a full 4GB then instead?

**Comment by nedellis** [comment] 2017-08-29 15:49
I tried the max which is 7680mb for me. In game for some reason the max allocated is still 4062. 
I don't know if this is a limitation of your pack or AtLauncher's. 

About why it doesn't affect you, maybe it's because you have better CPU. Have you tried your modpack on a slower machine? Like an i3 or an older i5?

**Comment by WesCook** [comment] 2017-08-29 18:50
I've not done performance testing on lower-end machines, no.  I've just relied on user reports.  Modded Minecraft is inherently difficult to run, and very CPU-bound, so that could be a factor.

Though lag spikes are often caused by a memory/GC limitation, so that would also have been my first guess.

You could try dropping the pack into a MultiMC instance instead to see if that has any impact.

**Comment by WesCook** [comment] 2017-09-07 10:08
I understand that there may be a valid concern with this issue, but as it appears to be quite dependent on hardware it unfortunately is not very actionable for me.  I can make recommendations such as trying other garbage collectors, though I don't believe there is any fix I can apply to the pack as a whole.

As such, I'm going to close this issue for now.

**Closed as completed by WesCook** 2017-09-07 10:08 UTC
