### ISSUE TITLE
Iron nuggets

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#22] opened 2017-08-04 11:40 UTC
Some problems with iron nuggets. I gathered some nuggets with strainer but i can't transform them into an iron ingot like with Immersive engineering nugget which btw seems they don't exist in jei.

[Screenshots.zip](https://github.com/WesCook/Homestead/files/1200208/Screenshots.zip)

**Comment by WesCook** [comment] 2017-08-04 12:28
Hello,

As described by the tooltip, nuggets need to be melted down in a smeltery to create ingots.  Unfortunately I made a mistake by leaving that recipe in, even though it's non-functional.  I've corrected this for the next version.

As for other nuggets not showing in JEI, that's also by design.  I wanted to keep a single version of any material to remove redundancies.  If you'd like to disable this though, you can turn off Item Hiding mode in the JEI settings.

Thanks for the report.

**Comment by WesCook** [comment] 2017-08-04 13:28
This issue has been fixed in v1.4.3.

**Closed as completed by WesCook** 2017-08-04 13:28 UTC
Labels: bug
