### ISSUE TITLE
black screen if i dig down

### ISSUE THREAD

**Issue by jordyweerwag** [WesCook/Homestead#100] opened 2019-01-18 17:06 UTC
issue is a black screen if i try to dig down on the ATLauncher on the twich app can't be installed because a error.

**Comment by WesCook** [comment] 2019-01-18 19:12
Hi Jordy,

Black screen issues are usually caused by Enhanced Visuals.  Can you try disabling that mod and seeing if it makes a difference?  Additionally, you may try disabling Mo' Bends as well.

Homestead is only on ATLauncher.  The version on Twitch is a different modpack.

Thanks.

**Comment by WesCook** [comment] 2019-03-18 11:40
Closing due to lack of followup.

**Closed by WesCook** 2019-03-18 11:40 UTC
